pipelines:
  demo_app_int:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
    stages:
      - build_app: # name of stage
          jobs:
            validate_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run hello-world
      - unit_test: # name of stage
          jobs:
            plan_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform plan"
      - push_image: # name of stage
          jobs:
            test_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform test via terratest"
      - deploy_app: # name of stage
          jobs:
            apply_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform apply"

  demo_app_qa:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
      upstream:
        pipeline: demo_app_int
        stage: deploy_app
    stages:
      - pull_image: # name of stage
          jobs:
            plan_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform plan"
      - deploy_app: # name of stage
          jobs:
            apply_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform apply"
      - api_test: # name of stage
          jobs:
            integration_test_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform integration test via rspec"

  demo_app_prod:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
      upstream:
        pipeline: demo_app_qa
        stage: api_test
    stages:
      - pull_image: # name of stage
          jobs:
            plan_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform plan"
      - deploy_app: # name of stage
          approval: manual
          jobs:
            apply_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform apply"
      - healthcheck: # name of stage
          jobs:
            healthcheck_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform healthcheck"