pipelines:
  demo_app_int:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
    environment_variables:
      IMAGE_NAME: gocd_demo_app 
      IMAGE_VERSION: latest
      DOCKERHUB_USERNAME: ashikansal #replace it by your own username
      ARTIFACT_STORE_ID: gocd_demo #replace it by your own artifact store id
    stages:
      - unit_test: # name of stage
          jobs:
            unit_test:
              artifacts:
                - build:
                    source: target/site/*
                    destination: test_reports/
              tabs:
                UT_report: test_reports/surefire-report.html
                UT_coverage: test_reports/jacoco/index.html
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm --name maven-test -v "$HOME/.m2":/root/.m2 -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6-jdk-8-slim mvn clean test
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm --name maven-test -v "$HOME/.m2":/root/.m2 -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6-jdk-8-slim mvn surefire-report:report-only && mvn site -DgenerateReports=false
      - build_and_push_image: # name of stage
          clean_workspace: false
          keep_artifacts: true
          jobs:
            build_and_push_image:
              artifacts:
                - external:
                    id: ${ARTIFACT_STORE_ID} #replace with your artifact id
                    store_id: ${ARTIFACT_STORE_ID} #replace with your artifact id
                    configuration:
                      options:
                        Image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}
                        Tag: ${GO_PIPELINE_LABEL}
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm --name maven-test -v "$HOME/.m2":/root/.m2 -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6-jdk-8-slim mvn clean compile package -DskipTests
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$GO_PIPELINE_LABEL -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
      - deploy_app: # name of stage
          clean_workspace: false
          jobs:
            deploy_app:
              tasks:
                - fetch:
                    artifact_origin: external
                    pipeline: demo_app_int
                    stage: build_and_push_image
                    job: build_and_push_image
                    artifact_id: ${ARTIFACT_STORE_ID}
                    run_if: passed
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./cleanup.sh gocd_demo_app_int            
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm -p 81:8080 --name gocd_demo_app_int -d $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      - health_check: # name of stage
          jobs:
            healthcheck:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - curl -f http://localhost:81/api/products
  demo_app_qa:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
      upstream:
        pipeline: demo_app_int
        stage: deploy_app
    environment_variables:
      IMAGE_NAME: gocd_demo_app 
      IMAGE_VERSION: latest
      DOCKERHUB_USERNAME: ashikansal #replace it by your own username
    stages:
      - deploy_app: # name of stage
          jobs:
            deploy_app:
              tasks: 
                - fetch:
                    artifact_origin: external
                    pipeline: demo_app_int
                    stage: build_and_push_image
                    job: build_and_push_image
                    artifact_id: ${ARTIFACT_STORE_ID}
                    run_if: passed
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./cleanup.sh gocd_demo_app_qa
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm -p 82:8080 --name gocd_demo_app_qa -d $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      - api_test: # name of stage
          jobs:
            api_test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "run api test"
      - health_check: # name of stage
          jobs:
            healthcheck:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - curl -f http://localhost:82/api/products  
  demo_app_prod:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
      qa_upstream:
        pipeline: demo_app_qa
        stage: api_test
      int_upstream:
        pipeline: demo_app_int
        stage: build_and_push_image
    environment_variables:
      IMAGE_NAME: gocd_demo_app 
      IMAGE_VERSION: latest
      DOCKERHUB_USERNAME: ashikansal #replace it by your own username
    stages:
      - deploy_app: # name of stage
          approval: manual
          jobs:
            deploy_app:
              tasks:
                - fetch:
                    artifact_origin: external
                    pipeline: demo_app_int
                    stage: build_and_push_image
                    job: build_and_push_image
                    artifact_id: ${ARTIFACT_STORE_ID}
                    run_if: passed
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./cleanup.sh gocd_demo_app_prod               
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm -p 83:8080 --name gocd_demo_app_prod -d $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      - health_check: # name of stage
          jobs:
            healthcheck:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - curl -f http://localhost:83/api/products