pipelines:
  demo_app_int:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
    stages:
      - unit_test: # name of stage
          jobs:
            unit_test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm --name maven-test -v "$HOME/.m2":/root/.m2 -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean test
      - build_jar: # name of stage
          jobs:
            build_jar:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker run --rm --name maven-test -v "$HOME/.m2":/root/.m2 -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8-slim mvn clean compile package

      - build_image: # name of stage
          jobs:
            test_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform test via terratest"
      - push_image: # name of stage
          jobs:
            test_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform test via terratest"
      - deploy_app: # name of stage
          jobs:
            apply_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform apply"

  demo_app_qa:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
      upstream:
        pipeline: demo_app_int
        stage: deploy_app
    stages:
      - pull_image: # name of stage
          jobs:
            plan_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform plan"
      - deploy_app: # name of stage
          jobs:
            apply_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform apply"
      - api_test: # name of stage
          jobs:
            integration_test_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform integration test via rspec"

  demo_app_prod:
    group: demo_app
    materials:
      mygit: #name of material
        git: https://github.com/ashikansal/gocd_demo.git
      upstream:
        pipeline: demo_app_qa
        stage: api_test
    stages:
      - pull_image: # name of stage
          jobs:
            plan_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform plan"
      - deploy_app: # name of stage
          approval: manual
          jobs:
            apply_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform apply"
      - healthcheck: # name of stage
          jobs:
            healthcheck_tf:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "terraform healthcheck"